# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntraserviceTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(31, 'Открыта'), (27, 'В работе'), (35, 'Требует уточнения'), (26, 'Отложена'), (29, 'Выполнена'), (28, 'Закрыта'), (30, 'Отменена'), (43, 'Передано в ИТ отдел'), (44, 'Передано в ТП'), (39, 'Передано АРС'), (40, 'Передано курьеру'), (42, 'Выполнено(АРС)'), (41, 'В работе(АРС)'), (45, 'Открыта(АРС)'), (47, 'Передано начальнику службы обеспечения'), (48, 'Передано начальнику отдела внутренней безопасности'), (49, 'Начальник АХО'), (51, 'Проверено КЦ'), (52, 'Передано в отдел Разработки'), (53, 'Передано РСП'), (54, 'Некомпетентность'), (55, 'Отложенный старт')])),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('edit_person', models.CharField(blank=True, max_length=128, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_mass', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('long_execution_notification', models.DateTimeField(blank=True, null=True)),
                ('executor_notification_count', models.IntegerField(blank=True, default=0, null=True)),
                ('admin_notification', models.DateTimeField(blank=True, null=True)),
                ('admin_notification_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntraserviceUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(max_length=128)),
                ('creator_fullname', models.CharField(blank=True, max_length=128, null=True)),
                ('creator_position', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=64, null=True)),
                ('room_number', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(11, 'Низкий'), (9, 'Средний'), (10, 'Высокий'), (12, 'Критический'), (13, 'АРС1'), (16, 'Регламент')], null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots')),
                ('is_mass', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.TelegramUser')),
                ('telegram_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.TelegramTask')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('intraservice_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.IntraserviceUser')),
                ('status', models.CharField(default='Не готов', max_length=10)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Executor'),
        ),
        migrations.AddField(
            model_name='intraservicetask',
            name='telegram_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Client'),
        ),
        migrations.AddField(
            model_name='executor',
            name='intraservice_task_active',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.IntraserviceTask'),
        ),
        migrations.AddField(
            model_name='executor',
            name='telegram_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.TelegramUser'),
        ),
    ]
