# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('ready_min', models.IntegerField(default=0)),
                ('work_min', models.IntegerField(default=0)),
                ('done_tasks', models.IntegerField(default=0)),
                ('mass_tasks', models.IntegerField(default=0)),
                ('postponed_tasks', models.IntegerField(default=0)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Executor')),
            ],
        ),
    ]
