# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170821_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraservicetask',
            name='pended_type',
            field=models.IntegerField(choices=[(0, 'Неизвестно'), (1, 'Критическая завка'), (2, 'Отложена сотрудником')], default=0),
        ),
    ]
