# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170821_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraservicetask',
            name='postponed_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Executor'),
        ),
    ]
