# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170821_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorstatistics',
            name='postponed_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executorstatistics',
            name='date',
            field=models.DateField(),
        ),
    ]
