# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_intraservicetask_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intraservicetask',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='intraservicetask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.IntraserviceTask'),
        ),
    ]
