# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_blockagejournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraservicetask',
            name='executor_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
