# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_intraservicetask_executor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorstatistics',
            name='cancel_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
