# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_executorstatistics_cancel_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
