# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_client_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
