# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_intraservicetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraservicetest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
