# Generated by Django 2.1.4 on 2019-01-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20171104_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='intraservice_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.IntraserviceUser'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='telegram_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='data.TelegramUser'),
        ),
        migrations.AlterField(
            model_name='executorstatistics',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Executor'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Executor'),
        ),
    ]
