# Generated by Django 2.1.4 on 2019-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20190110_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramtask',
            old_name='creator_fullname',
            new_name='shop_fullname',
        ),
        migrations.RemoveField(
            model_name='telegramtask',
            name='creator_position',
        ),
        migrations.RemoveField(
            model_name='telegramtask',
            name='room_number',
        ),
        migrations.AddField(
            model_name='telegramtask',
            name='block_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramtask',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
