# Generated by Django 2.1.4 on 2019-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20190112_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtask',
            name='team_viewer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
