# Generated by Django 2.1.4 on 2019-01-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_telegramtask_team_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtask',
            name='kkm_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
