# Generated by Django 2.1.5 on 2019-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20190121_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtask',
            name='true_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
